### ISSUE TITLE
Support 12-hour time formats

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/apple-health-ingester#25]
Currently the timestamp parsing fails if the user's phone is set to 12-hour in region settings. Additionally, it looks like 12-hour time may contain non-breaking spaces between the hour and the AM/PM, like as follows:

```
"2024-09-21 7:57:00\xe2\x80\xafam +1000"
```

The non-breaking space is a change in the ICU package: https://icu.unicode.org/download/72

Ref: https://github.com/irvinlim/apple-health-ingester/issues/24#issuecomment-2393304975

**Comment by tedpearson** [comment]
I'm curious how you traced it to the ICU package change. Care to share?

**Comment by irvinlim** [comment]
> I'm curious how you traced it to the ICU package change. Care to share?

Oh actually I simply tried to Google around for `e280af`, and that brought me to this issue: https://github.com/nodejs/node/issues/46123
